- hosts: nodes
  become: yes
  tasks:
  - name: Python Installation
    apt:
      name: python3
      state: latest
      update_cache: yes

  - name: Git Installation
    apt:
      name: git
      state: present
      update_cache: yes
